### ISSUE TITLE
[Bug]: Stuck while running with [Physics Mod]

### ISSUE THREAD

**Issue by MTZYWX7** [Brian-Wuest/MC-Prefab#294] opened 2024-11-07 07:17 UTC
### Minecraft Version

1.21.1

### Forge Version

Neoforge 21.1.72

### Mod Version

1.0.0

### Details

Conflict with the [Physics Mod] module, right clicking on the ground or right clicking to open the GUI causes it to freeze.
[Physics Mod] version is : Physics-Mod-pro-v172b-neoforge-1.21.0

**Comment by Brian-Wuest** [comment] 2024-11-08 12:43
You're going to have to provide a link to that as it doesn't appear to exist on CurseForge or Modrinth or at least not easily findable. Without having a downloadable copy of the mod to troubleshoot with I cannot determine what is wrong with the mod compatibility.

**Comment by MTZYWX7** [comment] 2024-11-08 13:36
Sorry, I didn't think carefully. Here is the download link：
https://www.patreon.com/posts/physics-mod-pro-105510754  or  https://www.patreon.com/file?h=105510754&m=320716234

**Comment by kaojinn** [comment] 2024-11-08 16:27
Due to this being a paid mod, and us not having a subscription to the
patreon for the author, we can't just take the mod, even for diagnostic
purposes.  It would be ethically dicey, since your access to it is
dependent upon your contributing to their work.  At this point, I would
suggest reaching out to the mod author about the issue, and see if they
have any suggestions, or the author can reach out to us and provide a copy
of the mod and permission.  It's the same kind of professional courtesy we
would expect from anyone else if our mod followed a pay structure.

**Comment by MTZYWX7** [comment] 2024-11-08 17:28
But this mod is currently free, and the professional version can be downloaded without the need for a membership. It is included in the MCMod website…（https://www.mcmod.cn/class/3460.html）
![屏幕截图(1208)](https://github.com/user-attachments/assets/ab77bf35-70fc-449f-b03d-08a5423345e4)

**Comment by MTZYWX7** [comment] 2024-11-08 17:44
I uploaded two screen recording files in Gofile cloud storage, one without Physics Mod operation and the other with Physics Mod module operation. This time, the Physics Mod module is the free version available on the Modrinth website.

https://modrinth.com/mod/physicsmod

https://gofile.io/d/k4ol6R

**Comment by Brian-Wuest** [comment] 2024-11-08 18:53
Thank you for the download links, I was able to duplicate the issue with the freely available version of the mod on CurseForge. 

Unfortunately I cannot determine the cause of the issue. There is a _significant_ lag spike in processing during a core Minecraft method call here: <https://github.com/Brian-Wuest/MC-Prefab/blob/683229eb05bdb9bb1b43dead75d546705f0649fe/Shared/src/com/prefab/gui/GuiBase.java#L331>

It gets past this line of code but it takes like 10 seconds to process it, which is a VERY long time and then just seems to loop forever after our code is complete.

Because Phsyics mod is closed source, I cannot look at their code to see what kind of Mixins or other type of code they might be using to change core Minecraft mechanics to change such functionality. 

Please note that when I disable the Physics mod this freezing behavior goes away.

As a results I would have to put this back onto the author of the Physics mod to determine what's going on to break this functionality as this is fairly basic and standard usage of Minecraft GUI rendering.

So, closing this issue.

**Closed as completed by Brian-Wuest** 2024-11-08 18:53 UTC
Labels: Bug, Mod Compatibility

**Comment by MTZYWX7** [comment] 2024-11-09 03:11
Thank you！
