### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by littlepianist** [Brian-Wuest/MC-Prefab#272] opened 2022-10-01 18:58 UTC
### Minecraft Version

1.19.2

### Forge Version

1.19.2-43.1.32

### Mod Version

1.9.2.2

### Details

Server configs do not work. I set the mineshaft option for the starter house to false on the server but players can still generate the mineshaft with the starter house blueprints.

**Comment by Brian-Wuest** [comment] 2022-10-10 11:23
This seems to be working fine for me when the server has the option turned off.

When the option to generate a mineshaft is turned off there is a blank spot between two checkboxes when using the House item. 

I have also confirmed with the House and Improved House items when generating the buildings in this manner on a server that the mineshaft does not generate even though the client-side option says to create a mineshaft.

![image](https://user-images.githubusercontent.com/13502068/194854638-0be0f582-f0ba-4be8-870d-0520d74aa97f.png)

Please provide more information about your particular setup otherwise this issue will be closed in one week.

**Comment by Brian-Wuest** [comment] 2022-10-16 12:40
Closing issue due to not being able to duplicate and no further information provided.

**Closed as completed by Brian-Wuest** 2022-10-16 12:40 UTC
Labels: Bug
