### ISSUE TITLE
Client Crashes when U build 2 structures at the same time. [1.12]

### ISSUE THREAD

**Issue by Fundryi** [Brian-Wuest/MC-Prefab#49] opened 2017-07-27 13:07 UTC
Version Infos:
Forge: Latest
Mod: Latest

Just wanted to share this.
I started a "structure" and thought what would happen if you start the second one at the same time its building the first one, aaand crash :(
Could be really "annoying" on a server if people use ur mod at the same time. 

Crash: https://gist.github.com/Fundryi/fabdac4b971b17d09744fa71b178dd4a

**Comment by Brian-Wuest** [comment] 2017-07-27 15:04
Interesting error.

What 2 structures were you generating and what dimension?

**Comment by Fundryi** [comment] 2017-07-27 15:11
These two: https://i.gyazo.com/2865d416be7efd9aa496cce1331b802f.jpg
And I'm in a "Void" world/Skyblock Generator.
Mod: https://minecraft.curseforge.com/projects/yunomakegoodmap

**Comment by Brian-Wuest** [comment] 2017-07-27 22:56
Thank you for the information. I was able to to duplicate the issue and figure out what the problem is. I will wait a while until releasing this fix since I just released 1.12 yesterday :smile:.

This has been an issue for a long time. I guess you are just the first person whom attempted this since this the enhancement of generating multiple structures at once was released.

It still lags the server but at least it doesn't completely freezes it.

**Comment by Fundryi** [comment] 2017-07-28 07:38
Cool that it is fixed but I really don't get Developer like u xD It a bug fix why don't just release the updated?
Let the people decide if they want it or not :P

**Comment by Brian-Wuest** [comment] 2017-07-28 10:40
I get were you are coming from and fortunately right now I have to the time to do a release :smile:. But usually why something isn't released right away is due to other factors. 

For instance, I could be working on a major overhaul(I'm not) that I haven't put out here yet and don't want to release partially done code (even if it's setup to not be used). For me this is a side project, I do this for the love of programming and the wonderful sandbox which Minecraft is, but because it is a side project, I don't have a lot of time to dedicate to it. (Hence why it took like a month to get to 1.12). 

I also have to consider how likely the bug is to be found and how critical of a bug it is. While it does crash the server which marks it high for a fix, the likely hood of people finding it is low. In this particular case the player has to build two buildings at the same time. Two Different players can build at the same time but when the SAME player tries to build two buildings is where the problem arises. My gut tells me that this is an edge case.

I am in the process of updating all 3 versions right now. I will close this issue once they are all approved on curse.

Thanks! 👍

**Comment by Fundryi** [comment] 2017-07-28 10:42
ahh okey cool :) thanks for the info.

**Comment by Brian-Wuest** [comment] 2017-07-28 11:07
The versions have been released and approved on curse forge.

Closing issue.

Thanks!

**Closed by Brian-Wuest** 2017-07-28 11:07 UTC
Labels: Bug, In Development
