### ISSUE TITLE
Request for Mod Devs

### ISSUE THREAD

**Issue by warderbrad** [Brian-Wuest/MC-Prefab#100] opened 2019-05-12 19:05 UTC
1. What version of Minecraft, Forge, and Mod are you running?
    1. Minecraft Version: Minecraft Version: 1.12.2
    1. Forge Version:  forge-14.23.5.2800
    1. Mod Version: prefab-1.3.0.26
1. What type of issue is this? Choose one of the following:
    1. **Enhancement** (Add/Change something)
         The ability to create custom prefab designs.  I am building a pack where I would like each player to get one prefab schematic before being sent off.  The schematic would hold only the most basic structure with no chests or anything.  What it would have though is a Stargate from the Stargate Network mod (https://www.curseforge.com/minecraft/mc-mods/stargate-network).

The idea being that they are sent off to build a new settlement but are to connect to the rest of the network.

Obviously, I am not asking you to build in support for the Stargate Network Mod, just make it possible to generate your own structures.  

One idea I had was that the structure being copied would exist in the world elsewhere.  Then the Prefab schematic would just copy the building in that location.

**Comment by Brian-Wuest** [comment] 2019-05-12 19:30
Duplicate of #68. 

The comment below also provides a link to a mod that allows you to do what you want. We didn't do this as a part of Prefab since it was already done.

https://github.com/Brian-Wuest/MC-Prefab/issues/68#issuecomment-453282885

Closing this issue.

**Closed by Brian-Wuest** 2019-05-12 19:30 UTC
Labels: Duplicate

**Comment by warderbrad** [comment] 2019-05-13 00:04
I had searched but didnt find that one.  My apologies.
