### ISSUE TITLE
[Idea] Customizable presets.

### ISSUE THREAD

**Issue by Fortanono** [Brian-Wuest/MC-Prefab#68] opened 2017-11-24 22:18 UTC
As a pack developer and builder, I was wondering if it would be possible to include a feature where we could push our own starter house or other presets to players.

**Comment by Brian-Wuest** [comment] 2017-11-24 23:13
I love the idea, and I think it's something that has come up before. The problem is with my own limitations specially with structure facing and entities.

For facing we manually make sure that the building is facing south in our test world before we scan it. If it's not facing south, the generated buildings don't work right and I haven't had time to figure out why.

Facing for mod blocks would also be very difficult to manage if they didn't use a vanilla object.

For entities such as armor stands and item frames, I just got a basic framework for those to be scannable. It's something we are playing with for the welcome center. And I don't even want to get into mod entities.

And finally, neither of us are in a creative mood at the moment and with the holidays coming up we probably won't start on anything until after that.

**Comment by Brian-Wuest** [comment] 2017-11-24 23:16
One thing i forgot to mention is the structure block available in vanilla. If your preset is less than or equal to a chunk in width/length, you could use that. It allows for saving of a structure. Don't know if you can generate an item to use for it though. I just know that it exists.

**Comment by LordRavenShadow** [comment] 2017-12-09 03:52
back in the day i use to use MrCrayfish's Construction Mod, 
https://www.youtube.com/watch?v=Gvn9M48BIws

it may give you some ideals  :)

**Comment by Brian-Wuest** [comment] 2017-12-09 13:51
Thanks! I will have to take a look at it. I just got back from a long vacation so it may take a while to get back into the swing of things.

**Comment by LordRavenShadow** [comment] 2017-12-10 15:23
just wanted to thank you  for the great job your doing

**Comment by Brian-Wuest** [comment] 2017-12-31 16:02
So I started to look at this and I **think** I have been able to figure out how to address the issue I have with my code where the structure has to face a certain way when scanning the blocks. I am testing this out now but might be a while before I am fully confident with it.

I will also be removing the ability for the player to choose the direction of the structure in the blueprint screens. The structure direction will instead always build in the direction the player is facing just like the Instant Bridge does. The preview function will stay around so they can still see how it will be built.

Once I have those 2 changes in-place I will be working on a way for mod pack developers to define their own structures. When I have that ironed out I will update this issue with my ideas.

**Note:** All of this will be done for Minecraft version 1.12.2 since the recipe changes in vanilla actually make the creation of custom structure items much easier.

**Comment by Brian-Wuest** [comment] 2018-01-20 15:46
I broke out the structure orientation button into it's own issue for now since that will be released soon.

**Comment by Brian-Wuest** [comment] 2018-06-18 00:19
Just as an update (since it's been 6 months), I still want to work on this but life\work and other mods have taken up a lot of my time.

**Comment by Brian-Wuest** [comment] 2019-01-10 22:38
So as an update on this. Kaojinn and I have discussed this and we will not be implementing Customizable pre-sets with this mod.

There is another mod out there which allows you to do this on CurseForge. It's called [Structurize](https://minecraft.curseforge.com/projects/structurize). It has a scan tool and a build tool which is exactly what I would have had to build.

I do not plan to make Prefab compatible with Structurize since our data structures are very different but this is an option for mod pack creators our there.

**Closed by Brian-Wuest** 2019-01-10 22:38 UTC
Labels: Enhancement, MC 1.12.2+
